<div class="row mt-3">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">

                <h1>Listar Categorias</h1>

                <div class="text-right">
                    <a href="/nova-categoria" class="btn btn-outline-primary">Nova Categoria</a>
                    <a href="/categorias/pdf" class="btn btn-outline-secondary">Gerar PDF</a>
                </div>

                <table class="table table-hover table-striped mt-3">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Descrição</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            /** @var \App\Entity\Category $category */
                            foreach ($categories as $category) {
                                echo "
                                    <tr>
                                        <td>{$category->getId()}</td>
                                        <td>{$category->getName()}</td>
                                        <td>{$category->getDescription()}</td>
                                        <td>
                                            <button onclick='confirmRemove({$category->getId()})' class='btn btn-danger'>Excluir</button>
                                            <a href='/categoria/editar?id={$category->getId()}' class='btn btn-warning'>Editar</a>
                                        </td>
                                    </tr>
                                ";
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    function confirmRemove(id) {
        if (confirm('Você realmente deseja excluir a categoria?')) {
            location.href='/categoria/excluir?id='+id;
        }
    }
</script>