<?php

$rows = '';

foreach ($categories as $category) {
    $rows .= "
        <tr>
            <td>{$category->getId()}</td>
            <td>{$category->getName()}</td>
            <td>{$category->getDescription()}</td>
        </tr>
    ";
}


return '
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<h1>Categorias dos Atendimentos</h1>

<div class="alert alert-info">
    <strong>Relatório Gerado em </strong> '.date('d/m/Y H:i:s').'
</div>

<table class="table table-hover table-striped mt-3">
    <thead class="thead-dark">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Descrição</th>
    </tr>
    </thead>
    <tbody>
        '.$rows.'
    </tbody>
</table>
';