<h1>Dashboard</h1>

<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <span><?=$quantityUser ?></span>
                <span>Usuários</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <span><?=$quantitySchedulingTotal ?></span>
                <span>Agendamentos</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <span><?=$quantitySchedulingFinished ?></span>
                <span>Agendamentos Finalizados</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <span><?=$quantitySchedulingCanceled ?></span>
                <span>Agendamentos Cancelados</span>
            </div>
        </div>
    </div>
</div>