<div class="row mt-5">
    <div class="col-md-9">
        <div class="jumbotron">
            <h1>Sistema de Atendimentos</h1>
        </div>
    </div>
    
    <div class="col-md-3">
        <?php
            if (isset($_GET['error'])) {
                echo "
                    <div class='alert alert-danger'>
                    {$_GET['error']}
                    </div>
                ";
            }
        ?>

        <form action="" method="post">
            <label for="email">Email</label><br>
            <input type="email" id="email" name="email" class="form-control" required>

            <br>
            <label for="password">Senha</label><br>
            <input type="password" id="password" name="password" class="form-control" required>

            <br>
            <button class="btn btn-primary btn-block">Entrar</button>
        </form>
    </div>
</div>