<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Atendimentos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/categorias">Categorias</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/agendamentos">Agendamentos</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <span class="text-white h3 mr-3">
            Olá, <?php echo \App\Security\Security::getUserLogged() ?>
        </span>
        <a class="btn btn-danger my-2 my-sm-0" href="/sair">Sair</a>
    </form>
  </div>
</nav>
